# Generated by Django 4.0.3 on 2022-03-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=256)),
                ('environment_type', models.CharField(choices=[('DEV', 'Development'), ('PROD', 'Production'), ('UAT', 'Staging')], max_length=4)),
                ('dataid', models.IntegerField()),
            ],
        ),
    ]
